"""
File used to define default colors, sizes and other static variables.
"""
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 900
WHITE_SQUARE_COLOR = (235, 236, 208, 255)
BLACK_SQUARE_COLOR = (119, 149, 86, 255)
NUMBER_OF_COLUMNS = 8
NUMBER_OF_ROWS = 8
SQUARE_SIZE = SCREEN_WIDTH/NUMBER_OF_COLUMNS
POSSIBLE_MOVE_HIGHLIGHT = (200, 52, 47, 125)

WHITE_COLOR_IDENTIFIER = 'w'

WHITE_PAWN_IDENTIFIER = 'wp'
WHITE_ROOK_IDENTIFIER = 'wR'
WHITE_KNIGHT_IDENTIFIER = 'wN'
WHITE_BISHOP_IDENTIFIER = 'wB'
WHITE_QUEEN_IDENTIFIER = 'wQ'
WHITE_KING_IDENTIFIER = 'wK'


BLACK_COLOR_IDENTIFIER = 'b'

BLACK_PAWN_IDENTIFIER = 'bp'
BLACK_ROOK_IDENTIFIER = 'bR'
BLACK_KNIGHT_IDENTIFIER = 'bN'
BLACK_BISHOP_IDENTIFIER = 'bB'
BLACK_QUEEN_IDENTIFIER = 'bQ'
BLACK_KING_IDENTIFIER = 'bK'

EMPTY_IDENTIFIER = '--'

ALPHACOLS = {0: 'a', 1: 'b', 2: 'c',  3: 'd', 4: 'e', 5: 'f', 6: 'g', 7: 'h'}
ALPHATONR = {'a': 0, 'b': 1,  'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7}
